[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "preswald-project"  
entrypoint = "hello.py"    

[branding]
name = "Malawi Football Visualization"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.sample_csv]
type = "csv"
path = "data/Dataset_Malawi_National_Football_Team_Matches"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"